/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import automaticbattle.Controlador;
import database.ProductorCombate;
import database.ProductorCombate.CombateInfo;
import java.util.ArrayList;

/**
 *
 * @author Algebro
 */
public class CampanaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CampanaPanel
     */
    
    VentanaDeJuego vj;
    int inicial=0;
    ArrayList<CombateInfo> listaCombates;
    
    
    public CampanaPanel(VentanaDeJuego vj) {
        initComponents();
        this.vj = vj;
        backgroundPanel1.setBackground("src/Images/backgrounds/back2.jpg");
        vj.setTitle(Controlador.GAME_NAME + " - Campaña");
        actualizarCombates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new GUI.BackgroundPanel();
        mision1 = new javax.swing.JButton();
        mision2 = new javax.swing.JButton();
        mision3 = new javax.swing.JButton();
        mision4 = new javax.swing.JButton();
        mision5 = new javax.swing.JButton();
        goright = new javax.swing.JButton();
        goleft = new javax.swing.JButton();

        backgroundPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        mision1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mision1.setForeground(new java.awt.Color(255, 102, 0));
        mision1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/icon70.png"))); // NOI18N
        mision1.setText("MISION");
        mision1.setBorderPainted(false);
        mision1.setContentAreaFilled(false);
        mision1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mision1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mision1ActionPerformed(evt);
            }
        });

        mision2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mision2.setForeground(new java.awt.Color(255, 102, 0));
        mision2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/icon70.png"))); // NOI18N
        mision2.setText("MISION");
        mision2.setBorderPainted(false);
        mision2.setContentAreaFilled(false);
        mision2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mision2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mision2ActionPerformed(evt);
            }
        });

        mision3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mision3.setForeground(new java.awt.Color(255, 102, 0));
        mision3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/icon70.png"))); // NOI18N
        mision3.setText("MISION");
        mision3.setBorderPainted(false);
        mision3.setContentAreaFilled(false);
        mision3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mision3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mision3ActionPerformed(evt);
            }
        });

        mision4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mision4.setForeground(new java.awt.Color(255, 102, 0));
        mision4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/icon70.png"))); // NOI18N
        mision4.setText("MISION");
        mision4.setBorderPainted(false);
        mision4.setContentAreaFilled(false);
        mision4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mision4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mision4ActionPerformed(evt);
            }
        });

        mision5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mision5.setForeground(new java.awt.Color(255, 102, 0));
        mision5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/icon70.png"))); // NOI18N
        mision5.setText("MISION");
        mision5.setBorderPainted(false);
        mision5.setContentAreaFilled(false);
        mision5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mision5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mision5ActionPerformed(evt);
            }
        });

        goright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/arrowright.png"))); // NOI18N
        goright.setBorderPainted(false);
        goright.setContentAreaFilled(false);
        goright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorightActionPerformed(evt);
            }
        });

        goleft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/arrowleft.png"))); // NOI18N
        goleft.setBorderPainted(false);
        goleft.setContentAreaFilled(false);
        goleft.setEnabled(false);
        goleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goleftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mision1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mision3)
                .addGap(254, 254, 254))
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(mision4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(mision5)
                .addGap(131, 131, 131))
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(mision2))
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(goleft)
                        .addGap(18, 18, 18)
                        .addComponent(goright)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(mision2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mision1)
                    .addComponent(mision3))
                .addGap(57, 57, 57)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mision5)
                    .addComponent(mision4))
                .addGap(54, 54, 54)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goleft)
                    .addComponent(goright))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mision1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mision1ActionPerformed
        Controlador.getInstance().indiceCombate = inicial;
        vj.setPanel(new SeleccionPanel(this.vj, mision1.getText()));
    }//GEN-LAST:event_mision1ActionPerformed

    private void mision2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mision2ActionPerformed
        Controlador.getInstance().indiceCombate = inicial+1;
        vj.setPanel(new SeleccionPanel(this.vj, mision2.getText()));
    }//GEN-LAST:event_mision2ActionPerformed

    private void mision3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mision3ActionPerformed
        Controlador.getInstance().indiceCombate = inicial+2;
        vj.setPanel(new SeleccionPanel(this.vj, mision3.getText()));
    }//GEN-LAST:event_mision3ActionPerformed

    private void mision4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mision4ActionPerformed
        Controlador.getInstance().indiceCombate = inicial+3;
        vj.setPanel(new SeleccionPanel(this.vj, mision4.getText()));
    }//GEN-LAST:event_mision4ActionPerformed

    private void gorightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorightActionPerformed
        inicial+=5;
        goleft.setEnabled(true);
        actualizarCombates();
    }//GEN-LAST:event_gorightActionPerformed

    private void mision5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mision5ActionPerformed
        Controlador.getInstance().indiceCombate = inicial+4;
        vj.setPanel(new SeleccionPanel(this.vj, mision5.getText()));
    }//GEN-LAST:event_mision5ActionPerformed

    private void goleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goleftActionPerformed
        inicial-=5;
        if(inicial<5)
            goleft.setEnabled(false);
        actualizarCombates();
    }//GEN-LAST:event_goleftActionPerformed

    private void clearCapitulos(){
        mision1.setText("NO DISPONIBLE");
        mision2.setText("NO DISPONIBLE");
        mision3.setText("NO DISPONIBLE");
        mision4.setText("NO DISPONIBLE");
        mision5.setText("NO DISPONIBLE");
    }
    
    private void actualizarCombates(){
        clearCapitulos();
        listaCombates = new ArrayList<>();
        for(int i=0; i<5; i++)
            listaCombates.add(ProductorCombate.getInstance().getCombateNivel(i+inicial));
        int j=0;
        for(CombateInfo CI : listaCombates){
            fijarCapitulo(CI, j, inicial+j);
            ++j;
        }
            
    }
    
    private void fijarCapitulo(CombateInfo CI, int num, int combindice){
        switch(num){
            case 0:
                mision1.setEnabled(CI!=null);
                if(CI!=null){
                    mision1.setText(combindice + ". " + CI.getNombre());
                    mision1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/" +CI.getImagen())));
                }else
                    mision1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/libro.png")));
                break;
            case 1:
                mision2.setEnabled(CI!=null);
                if(CI!=null){
                    mision2.setText(combindice + ". " + CI.getNombre());
                    mision2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/" +CI.getImagen())));
                }else
                    mision2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/libro.png")));
                break;
            case 2:
                mision3.setEnabled(CI!=null);
                if(CI!=null){
                    mision3.setText(combindice + ". " + CI.getNombre());
                    mision3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/" +CI.getImagen())));
                }else
                    mision3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/libro.png")));
                break;    
            case 3:
                mision4.setEnabled(CI!=null);
                if(CI!=null){
                    mision4.setText(combindice + ". " + CI.getNombre());
                    mision4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/" +CI.getImagen())));
                }else
                    mision4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/libro.png")));
                break;
            case 4:
                mision5.setEnabled(CI!=null);
                if(CI!=null){
                    mision5.setText(combindice + ". " + CI.getNombre());
                    mision5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/" +CI.getImagen())));
                }else
                    mision5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/libro.png")));
                break;    
                
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BackgroundPanel backgroundPanel1;
    private javax.swing.JButton goleft;
    private javax.swing.JButton goright;
    private javax.swing.JButton mision1;
    private javax.swing.JButton mision2;
    private javax.swing.JButton mision3;
    private javax.swing.JButton mision4;
    private javax.swing.JButton mision5;
    // End of variables declaration//GEN-END:variables
}
