/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import automaticbattle.Controlador;
import automaticbattle.Estadisticas;
import automaticbattle.Unidad;

/**
 *
 * @author Algebro
 */
public class EstadisticasPanel extends javax.swing.JPanel {

    /**
     * Creates new form EstadisticasPanel
     */
    
    VentanaDeJuego vj;
    Estadisticas E;
    public EstadisticasPanel(VentanaDeJuego VJ) {
        initComponents();
        vj = VJ;
        E= Controlador.getInstance().combateActual.estadisticas;
                backgroundPanel1.setBackground("src/Images/backgrounds/dark1.jpg");
        Controlador.getInstance().indiceCombate++;
        fijarInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new GUI.BackgroundPanel();
        jLabel1 = new javax.swing.JLabel();
        subPanel2 = new GUI.subPanelEstadisticas();
        subPanel1 = new GUI.subPanelEstadisticas();
        jugarButton = new javax.swing.JButton();
        consejo = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ESTADÍSTICAS");

        jugarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/letters/jugar100.png"))); // NOI18N
        jugarButton.setBorderPainted(false);
        jugarButton.setContentAreaFilled(false);
        jugarButton.setFocusPainted(false);
        jugarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarButtonActionPerformed(evt);
            }
        });
        jugarButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jugarButtonKeyPressed(evt);
            }
        });

        consejo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        consejo.setForeground(new java.awt.Color(255, 153, 153));
        consejo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consejo.setText("MENSAJE DE CONSEJO -");

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 424, Short.MAX_VALUE))
                            .addComponent(consejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jugarButton)
                        .addContainerGap())
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addComponent(subPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(consejo))
                    .addComponent(jugarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jugarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarButtonActionPerformed
        
        vj.setPanel(new CampanaPanel(this.vj));
    }//GEN-LAST:event_jugarButtonActionPerformed

    private void jugarButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jugarButtonKeyPressed
        
    }//GEN-LAST:event_jugarButtonKeyPressed

    
    private void fijarInformacion(){
        subPanel1.setEstadisticas(E,1);
        subPanel2.setEstadisticas(E,2);
        this.consejo.setText(getConsejo());
    }

    
    private String getConsejo(){
        if(E.getDanoEfectuadoUno() < E.getDanoEfectuadoDos())
            return "Equiparte un buen arma puede aumentar el daño que inflinges.";
        for(Unidad U : Controlador.getInstance().combateActual.inicialesUno)
            if(U.getArmadura() < 5+Controlador.getInstance().indiceCombate && U.getVida() < 160)
                return "Usar equipamiento defensivo dará más aguante a tus unidades.";
        int alcance=1;
        for(Unidad U : Controlador.getInstance().combateActual.inicialesUno)
            alcance = Math.max(alcance, U.getAlcance());
        if(alcance < 2)
            return "El uso de armas de largo alcance te permite atacar a distancia.";
        if(E.getCuracionUno() < 1)
            return "Personajes como el Paladín, aportan curación a tus unidades.";
        return "Intenta equilibrar a tus personajes para obtener un mejor resultado.";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BackgroundPanel backgroundPanel1;
    private javax.swing.JLabel consejo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jugarButton;
    private GUI.subPanelEstadisticas subPanel1;
    private GUI.subPanelEstadisticas subPanel2;
    // End of variables declaration//GEN-END:variables
}
