/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import automaticbattle.Controlador;
import automaticbattle.Estadisticas;

/**
 *
 * @author Algebro
 */
public class EstadisticasPanel extends javax.swing.JPanel {

    /**
     * Creates new form EstadisticasPanel
     */
    
    VentanaDeJuego vj;
    Estadisticas E;
    public EstadisticasPanel(VentanaDeJuego VJ) {
        initComponents();
        vj = VJ;
        E= Controlador.getInstance().combateActual.estadisticas;
                backgroundPanel1.setBackground("src/Images/backgrounds/dark1.jpg");
        fijarInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new GUI.BackgroundPanel();
        jLabel1 = new javax.swing.JLabel();
        subPanel2 = new GUI.subPanelEstadisticas();
        subPanel1 = new GUI.subPanelEstadisticas();
        jugarButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ESTADÍSTICAS");

        jugarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/letters/jugar100.png"))); // NOI18N
        jugarButton.setBorderPainted(false);
        jugarButton.setContentAreaFilled(false);
        jugarButton.setFocusPainted(false);
        jugarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarButtonActionPerformed(evt);
            }
        });
        jugarButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jugarButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jugarButton))
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addComponent(subPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(subPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jugarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jugarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarButtonActionPerformed
        Controlador.getInstance().indiceCombate++;
        vj.setPanel(new SeleccionPanel(this.vj));
    }//GEN-LAST:event_jugarButtonActionPerformed

    private void jugarButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jugarButtonKeyPressed
        char c = evt.getKeyChar();
        if(c >= '0' && c <= '9')
            Controlador.getInstance().setIndiceCombate(c-'0');
        else if(c=='k' ||c=='K')
            Controlador.getInstance().setIndiceCombate(Controlador.getInstance().indiceCombate+10);
    }//GEN-LAST:event_jugarButtonKeyPressed

    
    private void fijarInformacion(){
        subPanel1.setEstadisticas(E,1);
        subPanel2.setEstadisticas(E,2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BackgroundPanel backgroundPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jugarButton;
    private GUI.subPanelEstadisticas subPanel1;
    private GUI.subPanelEstadisticas subPanel2;
    // End of variables declaration//GEN-END:variables
}
