/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import automaticbattle.Controlador;
import automaticbattle.Unidad;
import database.Database;
import java.util.ArrayList;

/**
 *
 * @author Algebro
 */
public class SeleccionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CombatePanel
     */
    
    VentanaDeJuego vj;
    
    public SeleccionPanel(VentanaDeJuego VJ) {
        initComponents();
        this.vj = VJ;
        /*
        this.region1.generateZone();
        this.region1.setMap(Controlador.getInstance().combateActual.getTablero());
        */
    }

    ArrayList<Unidad> aliadas = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new GUI.BackgroundPanel();
        jButton3 = new javax.swing.JButton();
        sel1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoPanel = new javax.swing.JTextArea();
        sel2 = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("COMBATIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sel1.setText("PERSONAJE 1");
        sel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel1ActionPerformed(evt);
            }
        });

        infoPanel.setEditable(false);
        infoPanel.setColumns(20);
        infoPanel.setRows(5);
        jScrollPane2.setViewportView(infoPanel);

        sel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sel2.setText("PERSONAJE 2");
        sel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(sel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sel2))
                .addContainerGap(615, Short.MAX_VALUE))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(sel1)
                .addGap(18, 18, 18)
                .addComponent(sel2)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Controlador.getInstance().iniciaCombate(0, aliadas);
        
        vj.setPanel(new CombatePanel(vj));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel1ActionPerformed
        seleccionarPersonaje("Patricio Guerrero");
    }//GEN-LAST:event_sel1ActionPerformed

    private void sel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel2ActionPerformed
        seleccionarPersonaje("Joaquin Paladin");
    }//GEN-LAST:event_sel2ActionPerformed
    
    private void seleccionarPersonaje(String S){
        aliadas.add(Database.getInstance().getUnidadAliada(S));
        insertarInfo("Seleccionado " + S + "\nTotal unidades : " + aliadas.size());
    }
    
    public void insertarInfo(String info){
        this.infoPanel.setText(infoPanel.getText()+info+"\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BackgroundPanel backgroundPanel1;
    private javax.swing.JTextArea infoPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sel1;
    private javax.swing.JButton sel2;
    // End of variables declaration//GEN-END:variables
}
