/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import automaticbattle.Estadisticas;

/**
 *
 * @author Algebro
 */
public class subPanelEstadisticas extends javax.swing.JPanel {

    /**
     * Creates new form subPanelEstadisticas
     */
    public subPanelEstadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipo = new javax.swing.JLabel();
        saludInicial = new javax.swing.JLabel();
        efectuado = new javax.swing.JLabel();
        recibido = new javax.swing.JLabel();
        curacion = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(300, 250));

        equipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        equipo.setForeground(new java.awt.Color(204, 204, 255));
        equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipo.setText("EQUIPO UNO");

        saludInicial.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        saludInicial.setForeground(new java.awt.Color(153, 255, 153));
        saludInicial.setText("Salud inicial");

        efectuado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        efectuado.setForeground(new java.awt.Color(255, 255, 102));
        efectuado.setText("Daño efectuado");

        recibido.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        recibido.setForeground(new java.awt.Color(255, 102, 102));
        recibido.setText("Daño recibido");

        curacion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        curacion.setForeground(new java.awt.Color(102, 255, 102));
        curacion.setText("Curacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(efectuado)
                    .addComponent(recibido)
                    .addComponent(curacion)
                    .addComponent(saludInicial))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(equipo, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(equipo)
                .addGap(18, 18, 18)
                .addComponent(saludInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(efectuado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recibido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curacion)
                .addGap(0, 235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setEquipo(String Equipo){
        equipo.setText(Equipo);
    }
    
    public void setEstadisticas(Estadisticas E, int equipo){
        this.setEquipo("Equipo " + equipo);
        if(equipo==1){
            this.setSaludoInicial(E.getSaludInicialUno());
            this.setCuracion(E.getCuracionUno());
            this.setDanoEfectuado(E.getDanoEfectuadoUno());
            this.setDanoRecibido(E.getDanoRecibidoUno());
        }else{
            this.setSaludoInicial(E.getSaludInicialDos());
            this.setCuracion(E.getCuracionDos());
            this.setDanoEfectuado(E.getDanoEfectuadoDos());
            this.setDanoRecibido(E.getDanoRecibidoDos());
        }
    }
    
    public void setSaludoInicial(int inicial){
        this.saludInicial.setText(saludInicial.getText() + "  " + inicial);
    }
    public void setDanoRecibido(int dano){
        this.recibido.setText(recibido.getText() + "  " + dano);
    }
    public void setDanoEfectuado(int dano){
        this.efectuado.setText(efectuado.getText() + "  " + dano);
    }
    public void setCuracion(int cura){
        this.curacion.setText(curacion.getText() + "  " + cura);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel curacion;
    private javax.swing.JLabel efectuado;
    private javax.swing.JLabel equipo;
    private javax.swing.JLabel recibido;
    private javax.swing.JLabel saludInicial;
    // End of variables declaration//GEN-END:variables
}
